steps:
  - name: 3.9.6-eclipse-temurin-21-alpine
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/transactions', '.']
images: ['gcr.io/$PROJECT_ID/transactions']
options:
  logging: CLOUD_LOGGING_ONLY