steps:
  - name: 'gcr.io/cloud-builders/mvn:3.9.1'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/transactions', '.']
images: ['gcr.io/$PROJECT_ID/transactions']
options:
  logging: CLOUD_LOGGING_ONLY