steps:
  - name: 'gcr.io/cloud-builders/mvn:3.9.1'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/transactions', '.']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'transactions', '--image', 'gcr.io/$PROJECT_ID/transactions', '--region', 'us-central1' ]
images: ['gcr.io/$PROJECT_ID/transactions']
options:
  logging: CLOUD_LOGGING_ONLY